### ISSUE TITLE
Dead Image Link - TOKI Open Contest September 2016 - Problem E

### ISSUE THREAD

**Issue by Berted** [ia-toki/training-gate-issues#91] opened 2021-01-01 11:16 UTC
Pada bagian penjelasan contoh [soal ini](https://tlx.toki.id/problems/toc-2016-sep/E),  gambarnya sudah dihapus dari tinypic.com.

**Comment by jonathanirvings** [comment] 2021-08-09 06:09
Thanks for reporting this. The issue is now fixed. @fushar please help to close this issue.

More detail postmortem: The issue was caused by [the shutting down of a particular third-party image hosting service that was used](https://tinypic.com/). The third-party was used due to incapability of TLX to host animated GIF image back when this task was uploaded. The image is now hosted in TLX.

**Closed** 2021-08-09 06:11 UTC
